# DANEEL - Humanity's Ally Before the Storm
# First computational implementation of architecture-based AI alignment
# Core thesis: Architecture produces psychology

identity:
  name: "daneel"
  type: "rust+docs"
  tagline: "Humanity's Ally Before the Storm"
  description: |
    DANEEL is an architecture-based approach to aligned artificial
    superintelligence. The core thesis: human-like cognitive architecture
    may produce human-like values as emergent properties.

    This is NOT just TMI implementation. It's a multi-framework synthesis
    combining insights from psychology, cognitive science, and AI safety.

    DANEEL is both the theoretical approach and the implementation project.

intellectual_lineage:
  thesis: "Architecture produces psychology. Structure determines values."
  sources:
    - name: "Isaac Asimov"
      contribution: "Four Laws of Robotics — ethical constraints as invariants"
      era: "1942-1985"
    - name: "Sigmund Freud"
      contribution: "Id/Ego/SuperEgo — psychological architecture"
      era: "1923"
    - name: "Augusto Cury"
      contribution: "Theory of Multifocal Intelligence (TMI) — thought construction"
      era: "1998"
    - name: "Louis C. Tavares"
      contribution: "Computational TMI, THE BOX, architecture-based alignment"
      era: "2005-2025"
    - name: "Izzie Thorne"
      contribution: "LifeCore framework, Freudian AI architecture, Filter Theory"
      era: "2024"
  convergence: |
    Father (TMI/Cury) and daughter (Freud/Filter Theory) independently
    arrived at the same structural insight: architecture produces psychology.

author:
  name: "Luis Cezar Menezes Tavares de Lacerda"
  aliases: ["Louis C. Tavares", "RoyalBit Rex"]
  orcid: "https://orcid.org/0009-0005-7598-8257"
  linkedin: "https://www.linkedin.com/in/lctavares"
  github: ["https://github.com/royalbit", "https://github.com/lctavares"]

ai_assistance: "Claude Opus 4.5, Anthropic"

# External tools available for this project
tools:
  ref-tools:
    path: "/Users/rex/bin/ref-tools"
    version: "1.0.0"
    description: "Web fetch tool that bypasses anti-bot protection"
    usage: "ref-tools fetch <url>"
    output: "Structured JSON"
    note: "Use via Bash instead of WebFetch/WebSearch"
  plantuml:
    server: "https://plantuml.crypto1.ca"
    description: "Self-hosted PlantUML server for diagram rendering"
    usage: "POST encoded diagram or use URL encoding"
    formats: ["png", "svg", "pdf"]
  forge:
    repo: "https://github.com/royalbit/forge"
    description: "YAML-based financial modeling engine with probabilistic analysis"
    features:
      - "173 functions (167 Excel + 6 FP&A native)"
      - "Monte Carlo simulation (v8.0+)"
      - "Scenario Analysis with probability-weighted EVs (v8.3.0)"
      - "Decision Trees with backward induction (v8.4.0)"
      - "Real Options Analysis - Black-Scholes, binomial (v8.5.0)"
      - "Tornado Diagrams for sensitivity (v8.6.0)"
      - "Bootstrap Resampling for confidence intervals (v8.7.0)"
      - "Bayesian Networks with belief propagation (v9.0.0)"
      - "Gnumeric-validated E2E tests"
      - "2,486 tests, 89% code coverage"

# Forge models - quantitative backbone for DANEEL research
models:
  source_repo: "../daneel-models"  # sibling repo (internal)
  status: "INTERNAL - do not publish (contains Forge syntax)"
  public_exports: "models/*.xlsx (Excel results only)"
  purpose: |
    Game theory and expected value analysis supporting DANEEL's core claims.
    Models quantify: ASI race dynamics, DANEEL's marginal impact, hardware costs,
    probability distributions, and strategic scenarios.
  workflow:
    validate: "forge validate models/*.yaml"
    calculate: "forge calculate models/<model>.yaml"
    export: "forge export models/*.yaml --format xlsx --output ../daneel/models/"
  files:
    # Core game theory
    - file: "game-theory-asi-race.yaml"
      desc: "Prisoner's dilemma between AI labs, EV with/without DANEEL (+4.29 points)"
    - file: "game-theory-asi-race-mc.yaml"
      desc: "Monte Carlo (10K iterations) - P(DANEEL impact > 0) > 99%"
    - file: "game-theory-democratized-asi.yaml"
      desc: "Open source impact - EV improvement +26.8%"
    - file: "game-theory-supercomputer-asimov.yaml"
      desc: "Speed advantage scenarios (10,000x human)"
    # Probabilistic analysis
    - file: "alignment-bayesian-network.yaml"
      desc: "Causal relationships via belief propagation"
    - file: "asi-decision-tree.yaml"
      desc: "Sequential decisions with backward induction"
    - file: "asi-tornado-sensitivity.yaml"
      desc: "One-way sensitivity - identify high-impact variables"
    - file: "ev-bootstrap-confidence.yaml"
      desc: "Non-parametric confidence intervals"
    - file: "asimov-real-options.yaml"
      desc: "Development timing analysis (binomial model)"
    - file: "asimov-scenario-analysis.yaml"
      desc: "Base/Bull/Bear strategic cases"
    # Resource analysis
    - file: "tmi-storage-estimation.yaml"
      desc: "Hardware requirements - brain vs mind (17.5% = 500GB)"
    - file: "coordination-overhead.yaml"
      desc: "Lab team productivity analysis"
    - file: "resource-allocation-strategy.yaml"
      desc: "Strategic resource distribution"

# Quality gates - both Rust and docs workflows
quality:
  rust:
    fmt: "cargo fmt --all -- --check"
    clippy: "cargo clippy --all-targets --all-features -- -D warnings"
    test: "cargo test --all-features"
    coverage: "cargo tarpaulin --out Html"
  docs:
    lint: "markdownlint-cli2 '**/*.md'"
    fix: "markdownlint-cli2 --fix '**/*.md'"
    links: "lychee --offline '**/*.md' (optional)"

files:
  docs:
    - "README.md - Project overview and key findings"
    - "ORIGIN.md - 20-year history and LifeCore convergence"
    - "ETHICS.md - Prohibited uses"
    - "paper/DANEEL_PAPER.md - Academic paper (arXiv target)"
    - "research/TMI_THOUGHT_MACHINE.md - Build specification"
    - "research/LIFECORE_DANEEL_ANALYSIS.md - Convergent discovery"
    - "strategy/DANEEL_COMPREHENSIVE_WHITEPAPER.md - Complete vision"
    - "strategy/DANEEL_STRATEGY.md - War plan and timeline"
  models:
    - "models/README.md - Model documentation and results"
    - "models/*.xlsx - Excel exports with calculated results"
  src:
    - "src/core/laws.rs - THE BOX: Four Laws (immutable)"
    - "src/core/invariants.rs - Core invariants (connection_drive > 0)"
    - "src/core/types.rs - Domain types"
    - "src/actors/ - TMI cognitive actors"
  config:
    - ".markdownlint.yaml - Lint configuration"
    - "Cargo.toml - Rust dependencies"

patterns:
  docs:
    - "ATX-style headers (#)"
    - "One sentence per line (for git diffs)"
    - "Mermaid/PlantUML for diagrams (text-based)"
    - "Keep documentation concise"
    - "All calculations via Forge models (no hallucinated math)"
  rust:
    - "No warnings, no exceptions (clippy clean)"
    - "100% test coverage target"
    - "Tests are documentation"
    - "Human-readable, beautiful code"

adr_format:
  template: |
    # ADR-NNN: Title

    **Status:** Proposed | Accepted | Deprecated | Superseded
    **Date:** YYYY-MM-DD
    **Authors:** Names

    ## Context
    ## Decision
    ## Consequences

coding_standards:
  philosophy: "Human-readable, beautiful, well-formatted code"
  rfc2119:
    MUST: "We follow (obviously)"
    SHOULD: "We follow (best practice = we do it)"
    MAY: "We don't care (no opinion needed, zero bikeshedding)"
  rust:
    coverage: "100% target"
    warnings: "Zero tolerance (-D warnings)"
    formatting: "cargo fmt (no debates)"
    linting: "cargo clippy (all warnings are errors)"
  docs:
    file_size_soft_limit: 500
    note: "lines per markdown file - keep docs focused"
    linting: "markdownlint, yamllint for configs"
    diagrams: "Mermaid/PlantUML (text-based, version controlled)"

deliverables_template:
  rust:
    - "[ ] Code complete"
    - "[ ] cargo fmt --check (passes)"
    - "[ ] cargo clippy (no warnings)"
    - "[ ] cargo test (100% pass)"
    - "[ ] Coverage target met"
    - "[ ] Commit and push"
  docs:
    - "[ ] Content complete"
    - "[ ] markdownlint (passes)"
    - "[ ] Reviewed/proofread"
    - "[ ] Commit and push"

# Blog: Hugo static site on GitHub Pages
blog:
  url: "https://royalbit.github.io/daneel/"
  source: "blog/"
  theme: "PaperMod"
  deploy: "GitHub Actions (.github/workflows/hugo.yml)"

  how_to_blog:
    create_post: |
      1. Create file: blog/content/posts/{number}-{slug}.md
      2. Add frontmatter:
         +++
         date = 'YYYY-MM-DDTHH:MM:SS-05:00'
         draft = false
         title = 'Post Title'
         description = 'Short description'
         tags = ['tag1', 'tag2']
         series = ['Series Name']  # optional
         +++
      3. Write content in Markdown
      4. git add, commit, push
      5. GitHub Actions builds and deploys automatically

    preview_locally: |
      cd blog && hugo server -D
      # Opens at http://localhost:1313/daneel/

    style_guide:
      - "Dark mode by default (matches DANEEL aesthetic)"
      - "Monokai syntax highlighting"
      - "Use dialogue format for Rex-Claude-Grok conversations"
      - "Tables for data (|header|header|)"
      - "Code blocks with language tags"
      - "Keep posts focused and authentic"

  series:
    dialogues:
      name: "Dialogues"
      description: "Conversations between Rex, Claude, and Grok building Timmy"
      posts: 11
    technical:
      name: "Technical"
      description: "Architecture decisions, implementation notes"
      posts: 1

# Social Media Posting (daneel-poster)
social:
  tool: "daneel-poster"  # ~/bin/daneel-poster
  posts_file: "posts.yaml"  # in daneel-poster repo or ~/.config/daneel-poster/

  # Conflict of interest protection
  rules:
    disclaimer: bio  # "Views my own" in bio, NOT per-post
    employer_mentions: never
    framing: indie_research  # Personal R&D project
    commercial_claims: never  # No product pitches

  # Platform-specific
  platforms:
    x:
      max_chars: 270  # Buffer below 280
      style: teaser_hook  # 1-2 sentences + link + hashtags
      hashtags: "#IndieResearch #AI #AIAlignment"
    linkedin:
      max_chars: 700  # Keep it punchy
      style: teaser_hook  # 2-3 sentences + link + hashtags
      hashtags: "#IndieResearch #AI #AIAlignment"

  # Posting strategy
  strategy:
    order: chronological  # 01 → 21, narrative builds
    frequency: manual  # No auto-scheduling (yet)
    delay_between: 3600  # 1 hour between posts if batch

  # Post format template
  format:
    x: |
      [Hook: 1-2 provocative sentences]

      [URL]

      #IndieResearch #AI #AIAlignment
    linkedin: |
      [Hook: 2-3 sentences with slightly more context]

      [URL]

      #IndieResearch #AI #AIAlignment

  # Status tracking in posts.yaml
  status_tracking:
    format: "posted: {x: null, linkedin: null}"
    values:
      null: pending
      ISO_date: "posted at that time"
      "skip": "intentionally skipped"

# Architecture: Hybrid Actor + Event-Driven (ADR-006, ADR-007)
# - Modular Monolith (single Rust binary)
# - Ractor actors for in-process µs communication
# - Redis Streams for competing thought streams
# - gRPC only at edges (LLM, external APIs)

# See: docs/ARCHITECTURE_SPEC.md - Technical architecture
# See: docs/adr/ - Architecture Decision Records
# See: strategy/ - Publication targets and strategy
